name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what the bug is.
      placeholder: e.g., Crash when opening Logs tab on Android 14
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the behavior?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Tell us what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened? Include error messages and logs if possible.
  - type: dropdown
    id: platform
    attributes:
      label: Platform(s)
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - macOS
        - Windows
        - Linux
  - type: input
    id: version
    attributes:
      label: App version/build
      placeholder: e.g., 1.0.0+12
  - type: textarea
    id: logs
    attributes:
      label: Logs, screenshots, or screen recordings
      description: Drag and drop to attach files.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
