#!/usr/bin/env bash
set -euo pipefail

# Generate assets/data/version.yaml based on provided environment variables.
# Expected envs:
#   VERSION_NAME       (e.g., v0.0.1)
#   VERSION_NUMBER     (e.g., 3) — integer
#   VERSION_DESCRIBE   (e.g., v0.0.1-3-gabc1234)
# Optional env:
#   BUILD_TIME_UTC     (defaults to current UTC time)

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
ASSET_PATH="$ROOT_DIR/assets/data/version.yaml"

VERSION_NAME=${VERSION_NAME:-}
VERSION_NUMBER=${VERSION_NUMBER:-}
VERSION_DESCRIBE=${VERSION_DESCRIBE:-}
BUILD_TIME_UTC=${BUILD_TIME_UTC:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}

if [[ -z "$VERSION_NAME" || -z "$VERSION_NUMBER" || -z "$VERSION_DESCRIBE" ]]; then
  echo "gen_version_yaml.sh: Missing required env(s)." >&2
  echo "Required: VERSION_NAME, VERSION_NUMBER, VERSION_DESCRIBE" >&2
  exit 1
fi

mkdir -p "$(dirname "$ASSET_PATH")"
cat > "$ASSET_PATH" <<EOF
# Generated by scripts/gen_version_yaml.sh — do not edit manually
version:
  name: "${VERSION_NAME}"
  number: ${VERSION_NUMBER}
  describe: "${VERSION_DESCRIBE}"
  build_time_utc: "${BUILD_TIME_UTC}"
EOF

echo "Wrote $ASSET_PATH with name=${VERSION_NAME}, number=${VERSION_NUMBER}, describe=${VERSION_DESCRIBE}"
