// Generated file - do not edit
// Generated by native_splash_screen_cli

import native_splash_screen_macos

class DebugNativeSplashScreenConfiguration: NativeSplashScreenConfigurationProvider {

    // MARK: - Splash screen properties
    let windowWidth: Int = 450
    let windowHeight: Int = 225

    // MARK: - Window Title
    let windowTitle: String = "Multi-platform multi-mesh controller"

    // MARK: - Animation control
    let withAnimation: Bool = true

    // MARK: - Image properties
    let imageFileName: String = "splash_screen_debug.png"
    let imageWidth: Int = 400
    let imageHeight: Int = 200
}
